twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        formato_fecha: '%app.formato_fecha%'
        categoria_repository: '@App\Repository\CategoriaRepository'


when@test:
    twig:
        strict_variables: true
